name: Daily Unegui Scraper

on:
  schedule:
    - cron: '0 1 * * *'  # Every day at 01:00 UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python Clean/data/scrape_rental.py  # <-- Corrected file path

      - name: Commit updated cache (optional)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Clean/data/scraped_urls.json  # <-- Also update path here if needed
          git commit -m "Update scraped URLs cache" || echo "No changes to commit"
          git push
